### ISSUE TITLE
Question: Does the jerky-zick-zack move work in practice?

### ISSUE THREAD

**Issue by talldonkey** [sn4k3/Ender3#12]
Hi, just wondering how useful you find the jerky zick zack move.  I notice that you have it commented out (or its not there) on some profiles, especially Ender-3 BLtouch printer profile.

G91 ; Use relative mode
; Make some jerky zick-zack move at the beginning
; This is supposed to get rid of residue at the nozzle
;G1 X1.0 Y5.0 Z-0.1 E-1.0 F7200 ; X6 Y10 Z0.1, retract a tiny bit / 120mm/s
;G1 X1.0 Y-5.0 Z0.1 E2.0 F7200 ; X7 Y5 Z0.2 extrude a tiny bit
;G1 X2.0 Y5.0 Z-0.1 F7200 ; X9 Y10 Z0.1
;G1 X2.0 Y-5.0 Z0.1 F7200 ; X11 Y5 Z0.2
;G1 X2.0 Y5.0 F7200 ; X13 Y10
;G1 X2.0 Y-5.0 F7200 ; X15 Y5

**Comment by sn4k3** [comment]
Hello, It's disable on other for safety, if nozzle goes under bed it can crash and make damage somewhere.
It's not very usefull since it need be very close from bed, and i can't provide that on universal profiles. 
The purge line is ok.
It would be more usefull if your printer had a cleaning zone with brushes or something to clean nozzle.
